---
#Configuracao padrao do pool iottadra

- name: Desproteger resolv.conf
  hosts: all
  tasks:
    - command: "chattr -i /etc/resolv.conf"

- name: Atualizar resolv.conf
  hosts: all
  tasks:
     - copy: src=etc/resolv.conf dest=/etc/resolv.conf

- name: Proteger resolv.conf
  hosts: all
  tasks:
    - command: "chattr +i /etc/resolv.conf"

- name: alterar os arquivos motd
  hosts: all
  tasks:
     - copy: src=etc/motd dest=/etc/motd
       
- name: alterar os arquivos issue
  hosts: all
  tasks:
     - copy: src=etc/issue dest=/etc/issue

- name: alterar os arquivos issue.net
  hosts: all
  tasks:
     - copy: src=etc/issue.net dest=/etc/issue.net

- name: alterar o arquivo do repositorio
  hosts: all
  tasks:
     - copy: src=etc/sources.list dest=/etc/apt/sources.list

- name: atualizar o repositorio
  hosts: all
  tasks:
    - apt: update_cache=yes
